version: "2.4"

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app:delegated
    ports:
      - 80:${APP_PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./db:/data/db
      - ./setup-db:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:${DATABASE_PORT}/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
